function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // obj_start
	global.__objectDepths[1] = 0; // obj_view_init
	global.__objectDepths[2] = 0; // Audio
	global.__objectDepths[3] = 0; // Sound
	global.__objectDepths[4] = 0; // Input
	global.__objectDepths[5] = 0; // g
	global.__objectDepths[6] = 0; // p
	global.__objectDepths[7] = 0; // f
	global.__objectDepths[8] = 0; // RoomData
	global.__objectDepths[9] = 0; // GameObjectData
	global.__objectDepths[10] = 0; // Rando
	global.__objectDepths[11] = 0; // DeathScreen
	global.__objectDepths[12] = 0; // NextLifeScreen
	global.__objectDepths[13] = 0; // GameOverScreen
	global.__objectDepths[14] = 0; // ContinueSaveScreen
	global.__objectDepths[15] = 0; // FileSelect
	global.__objectDepths[16] = 0; // TitleScreen
	global.__objectDepths[17] = 0; // Overworld
	global.__objectDepths[18] = 0; // GameObjectMgr
	global.__objectDepths[19] = 0; // GameObject
	global.__objectDepths[20] = 0; // GameObjectA
	global.__objectDepths[21] = 0; // Lonk
	global.__objectDepths[22] = 0; // GameObjectB
	global.__objectDepths[23] = 0; // GOB1
	global.__objectDepths[24] = 0; // Enemy
	global.__objectDepths[25] = 0; // Boss
	global.__objectDepths[26] = 0; // Horsehead01
	global.__objectDepths[27] = 0; // Helmethead01
	global.__objectDepths[28] = 0; // HelmetheadHead01
	global.__objectDepths[29] = 0; // Rebonack01A
	global.__objectDepths[30] = 0; // Rebonack01B
	global.__objectDepths[31] = 0; // Carock01
	global.__objectDepths[32] = 0; // Gooma01
	global.__objectDepths[33] = 0; // Barba01
	global.__objectDepths[34] = 0; // Thunderbird01
	global.__objectDepths[35] = 0; // ShadowLonk01
	global.__objectDepths[36] = 0; // Ganon
	global.__objectDepths[37] = 0; // Ganon1
	global.__objectDepths[38] = 0; // Ganon2
	global.__objectDepths[39] = 0; // Ganon3
	global.__objectDepths[40] = 0; // Ache01
	global.__objectDepths[41] = 0; // Aneru01
	global.__objectDepths[42] = 0; // Aruroda01
	global.__objectDepths[43] = 0; // Atta01
	global.__objectDepths[44] = 0; // Backwall01
	global.__objectDepths[45] = 0; // Bagin01
	global.__objectDepths[46] = 0; // Bago01
	global.__objectDepths[47] = 0; // Balshot01
	global.__objectDepths[48] = 0; // Blaze01
	global.__objectDepths[49] = 0; // Boggnipp01
	global.__objectDepths[50] = 0; // Boon01
	global.__objectDepths[51] = 0; // Bot
	global.__objectDepths[52] = 0; // Bot_A
	global.__objectDepths[53] = 0; // Bot_B
	global.__objectDepths[54] = 0; // BoBoA
	global.__objectDepths[55] = 0; // BubbA
	global.__objectDepths[56] = 0; // CappA
	global.__objectDepths[57] = 0; // DairA
	global.__objectDepths[58] = 0; // DeelA
	global.__objectDepths[59] = 0; // DoomA
	global.__objectDepths[60] = 0; // FokkA
	global.__objectDepths[61] = 0; // FokuA
	global.__objectDepths[62] = 0; // GeldA
	global.__objectDepths[63] = 0; // GlzmA
	global.__objectDepths[64] = 0; // GeruA
	global.__objectDepths[65] = 0; // GeruB
	global.__objectDepths[66] = 0; // GiruA
	global.__objectDepths[67] = 0; // GoriA
	global.__objectDepths[68] = 0; // Growkke
	global.__objectDepths[69] = 0; // MoblB
	global.__objectDepths[70] = 0; // GumaA
	global.__objectDepths[71] = 0; // IrKnA
	global.__objectDepths[72] = 0; // LeevA
	global.__objectDepths[73] = 0; // LowdA
	global.__objectDepths[74] = 0; // MagnA
	global.__objectDepths[75] = 0; // MagoA
	global.__objectDepths[76] = 0; // Mau_A
	global.__objectDepths[77] = 0; // MegmA
	global.__objectDepths[78] = 0; // Moa_A
	global.__objectDepths[79] = 0; // Moa_B
	global.__objectDepths[80] = 0; // MoblA
	global.__objectDepths[81] = 0; // MobyA
	global.__objectDepths[82] = 0; // Myu_A
	global.__objectDepths[83] = 0; // Octorok01
	global.__objectDepths[84] = 0; // Ra__A
	global.__objectDepths[85] = 0; // Slog
	global.__objectDepths[86] = 0; // Snaraa
	global.__objectDepths[87] = 0; // StfnA
	global.__objectDepths[88] = 0; // StalA
	global.__objectDepths[89] = 0; // Stallakk
	global.__objectDepths[90] = 0; // TektA
	global.__objectDepths[91] = 0; // TonnA
	global.__objectDepths[92] = 0; // TyellManager
	global.__objectDepths[93] = 0; // Tyell
	global.__objectDepths[94] = 0; // Wheep
	global.__objectDepths[95] = 0; // WizaA
	global.__objectDepths[96] = 0; // WosuA
	global.__objectDepths[97] = 0; // ZoraA
	global.__objectDepths[98] = 0; // Kakusu
	global.__objectDepths[99] = 0; // KakusuA
	global.__objectDepths[100] = 0; // KakusuB
	global.__objectDepths[101] = 0; // Kakusu000
	global.__objectDepths[102] = 0; // Kakusu001
	global.__objectDepths[103] = 0; // Kakusu002
	global.__objectDepths[104] = 0; // Kakusu003
	global.__objectDepths[105] = 0; // Kakusu004
	global.__objectDepths[106] = 0; // Kakusu005
	global.__objectDepths[107] = 0; // Kakusu006
	global.__objectDepths[108] = 0; // Kakusu007
	global.__objectDepths[109] = 0; // Kakusu008
	global.__objectDepths[110] = 0; // Kakusu009
	global.__objectDepths[111] = 0; // Kakusu010
	global.__objectDepths[112] = 0; // Kakusu011
	global.__objectDepths[113] = 0; // Kakusu012
	global.__objectDepths[114] = 0; // Kakusu013
	global.__objectDepths[115] = 0; // Kakusu014
	global.__objectDepths[116] = 0; // GOB2
	global.__objectDepths[117] = 0; // Spawner
	global.__objectDepths[118] = 0; // SpawnerHostile
	global.__objectDepths[119] = 0; // Spawner_Boggnipp
	global.__objectDepths[120] = 0; // SpBaA
	global.__objectDepths[121] = 0; // SpPoA
	global.__objectDepths[122] = 0; // SpBuA
	global.__objectDepths[123] = 0; // SpDrA
	global.__objectDepths[124] = 0; // SpGrA
	global.__objectDepths[125] = 0; // SpMaA
	global.__objectDepths[126] = 0; // SpMoA
	global.__objectDepths[127] = 0; // SpRoA
	global.__objectDepths[128] = 0; // SpWoA
	global.__objectDepths[129] = 0; // SpBlA
	global.__objectDepths[130] = 0; // Spawner_FallingBlock
	global.__objectDepths[131] = 0; // SpawnerFriendly
	global.__objectDepths[132] = 0; // SpNPA
	global.__objectDepths[133] = 0; // SpawnerStab
	global.__objectDepths[134] = 0; // SpStA
	global.__objectDepths[135] = 0; // NPC
	global.__objectDepths[136] = 0; // NPC_0
	global.__objectDepths[137] = 0; // NPC_1
	global.__objectDepths[138] = 0; // NPC_2
	global.__objectDepths[139] = 0; // NPC_3
	global.__objectDepths[140] = 0; // NPC_4
	global.__objectDepths[141] = 0; // NPC_5
	global.__objectDepths[142] = 0; // NPC_6
	global.__objectDepths[143] = 0; // NPC_7
	global.__objectDepths[144] = 0; // NPC_8
	global.__objectDepths[145] = 0; // NPC_9
	global.__objectDepths[146] = 0; // NPC_A
	global.__objectDepths[147] = 0; // NPC_B
	global.__objectDepths[148] = 0; // NPC_C
	global.__objectDepths[149] = 0; // NPC_D
	global.__objectDepths[150] = 0; // Zelda
	global.__objectDepths[151] = 0; // Item
	global.__objectDepths[152] = 0; // ItmA0
	global.__objectDepths[153] = 0; // ItmA1
	global.__objectDepths[154] = 0; // ItmA2
	global.__objectDepths[155] = 0; // ItmA3
	global.__objectDepths[156] = 0; // ItmA4
	global.__objectDepths[157] = 0; // ItmA5
	global.__objectDepths[158] = 0; // ItmA6
	global.__objectDepths[159] = 0; // ItmA7
	global.__objectDepths[160] = 0; // ItmA8
	global.__objectDepths[161] = 0; // ItmA9
	global.__objectDepths[162] = 0; // ItmAA
	global.__objectDepths[163] = 0; // ItmAB
	global.__objectDepths[164] = 0; // ItmAC
	global.__objectDepths[165] = 0; // ItmAD
	global.__objectDepths[166] = 0; // ItmAE
	global.__objectDepths[167] = 0; // ItmAF
	global.__objectDepths[168] = 0; // ItmK0
	global.__objectDepths[169] = 0; // ItmK1
	global.__objectDepths[170] = 0; // ItmK2
	global.__objectDepths[171] = 0; // ItmK3
	global.__objectDepths[172] = 0; // ItmK4
	global.__objectDepths[173] = 0; // ItmK5
	global.__objectDepths[174] = 0; // ItmK6
	global.__objectDepths[175] = 0; // ItmK7
	global.__objectDepths[176] = 0; // ItmK8
	global.__objectDepths[177] = 0; // ItmK9
	global.__objectDepths[178] = 0; // ItmKA
	global.__objectDepths[179] = 0; // ItmKB
	global.__objectDepths[180] = 0; // ItmD8
	global.__objectDepths[181] = 0; // ItmB0
	global.__objectDepths[182] = 0; // ItmB1
	global.__objectDepths[183] = 0; // ItmC0
	global.__objectDepths[184] = 0; // ItmC1
	global.__objectDepths[185] = 0; // ItmC2
	global.__objectDepths[186] = 0; // ItmC3
	global.__objectDepths[187] = 0; // ItmC4
	global.__objectDepths[188] = 0; // ItmC5
	global.__objectDepths[189] = 0; // ItmD0
	global.__objectDepths[190] = 0; // ItmE0
	global.__objectDepths[191] = 0; // ItmF0
	global.__objectDepths[192] = 0; // ItmG0
	global.__objectDepths[193] = 0; // ItmH0
	global.__objectDepths[194] = 0; // ItmS0
	global.__objectDepths[195] = 0; // Elevator
	global.__objectDepths[196] = 0; // ElevA
	global.__objectDepths[197] = 0; // ElevatorB
	global.__objectDepths[198] = 0; // LoDoA
	global.__objectDepths[199] = 0; // ReFaA
	global.__objectDepths[200] = 0; // CrHoA
	global.__objectDepths[201] = 0; // BarrA
	global.__objectDepths[202] = 0; // Barrier2
	global.__objectDepths[203] = 0; // FaBlA
	global.__objectDepths[204] = 0; // BlckB
	global.__objectDepths[205] = 0; // SpikeTrap
	global.__objectDepths[206] = 0; // SpTrA
	global.__objectDepths[207] = 0; // SpTrB
	global.__objectDepths[208] = 0; // SpTrC
	global.__objectDepths[209] = 0; // SpikeTrapD
	global.__objectDepths[210] = 0; // Switch
	global.__objectDepths[211] = 0; // SwchA
	global.__objectDepths[212] = 0; // SwchB
	global.__objectDepths[213] = 0; // PushA
	global.__objectDepths[214] = 0; // PushableRefresher
	global.__objectDepths[215] = 0; // Target
	global.__objectDepths[216] = 0; // TargA
	global.__objectDepths[217] = 0; // FiRoA
	global.__objectDepths[218] = 0; // Torch
	global.__objectDepths[219] = 0; // TorchA
	global.__objectDepths[220] = 0; // ArenaGate
	global.__objectDepths[221] = 0; // ArenaGateA
	global.__objectDepths[222] = 0; // Cucco
	global.__objectDepths[223] = 0; // Blooby
	global.__objectDepths[224] = 0; // Eyenocc
	global.__objectDepths[225] = 0; // SmasherTrapManager
	global.__objectDepths[226] = 0; // SmasherTrap
	global.__objectDepths[227] = 0; // SmasherTrap01
	global.__objectDepths[228] = 0; // GameObjectC
	global.__objectDepths[229] = 0; // ProjectileHostile
	global.__objectDepths[230] = 0; // Axe
	global.__objectDepths[231] = 0; // Bolo
	global.__objectDepths[232] = 0; // Boomerang
	global.__objectDepths[233] = 0; // Bullet1
	global.__objectDepths[234] = 0; // Bullet2
	global.__objectDepths[235] = 0; // Drop
	global.__objectDepths[236] = 0; // Fireball1
	global.__objectDepths[237] = 0; // Fireball2
	global.__objectDepths[238] = 0; // Flame1
	global.__objectDepths[239] = 0; // Flame2
	global.__objectDepths[240] = 0; // Mace1
	global.__objectDepths[241] = 0; // Mace2
	global.__objectDepths[242] = 0; // RisingBubble
	global.__objectDepths[243] = 0; // Rock1
	global.__objectDepths[244] = 0; // Rock2
	global.__objectDepths[245] = 0; // Rock3
	global.__objectDepths[246] = 0; // SoundWave
	global.__objectDepths[247] = 0; // Spear
	global.__objectDepths[248] = 0; // SwordBeam
	global.__objectDepths[249] = 0; // BossExplosion
	global.__objectDepths[250] = 0; // SpikeBall1
	global.__objectDepths[251] = 0; // ProjectileFriendly
	global.__objectDepths[252] = 0; // GameObjectD
	global.__objectDepths[253] = 0; // Platform
	global.__objectDepths[254] = 0; // PlatformA
	global.__objectDepths[255] = 0; // PlatformB
	global.__objectDepths[256] = 0; // PlatformCloud
	global.__objectDepths[257] = 0; // PlatformRaft
	global.__objectDepths[258] = 0; // BurnableMgr
	global.__objectDepths[259] = 0; // GameObjectE
	global.__objectDepths[260] = 0; // Challenge
	global.__objectDepths[261] = 0; // Challenge_BlockConfiguration
	global.__objectDepths[262] = 0; // Challenge_IntermittentPlatformSequence
	global.__objectDepths[263] = 0; // Challenge_SwitchA
	global.__objectDepths[264] = 0; // Challenge_SwitchB
	global.__objectDepths[265] = 0; // Challenge_SwitchC
	global.__objectDepths[266] = 0; // Challenge_SwitchD
	global.__objectDepths[267] = 0; // MiniGame
	global.__objectDepths[268] = 0; // MnGmA
	global.__objectDepths[269] = 0; // TogglingPathDirection
	global.__objectDepths[270] = 0; // TogglingPathDirectionA
	global.__objectDepths[271] = 0; // TogglingPathDirectionB
	global.__objectDepths[272] = 0; // Challenge_DefeatAll
	global.__objectDepths[273] = 0; // Challenge_DefeatAllA
	global.__objectDepths[274] = 0; // Challenge_LightTorches
	global.__objectDepths[275] = 0; // Challenge_LightTorchesA
	global.__objectDepths[276] = 0; // Challenge_SpellSequence
	global.__objectDepths[277] = 0; // Challenge_SpellSequenceA
	global.__objectDepths[278] = 0; // Challenge_PushableMatching1
	global.__objectDepths[279] = 0; // Challenge_Secret01
	global.__objectDepths[280] = 0; // GameObjectF
	global.__objectDepths[281] = 0; // Cutscene
	global.__objectDepths[282] = 0; // Cutscene_SariaBridge
	global.__objectDepths[283] = 0; // Cutscene_MagicalKeyHouse
	global.__objectDepths[284] = 0; // Cutscene_EnterFromChimney
	global.__objectDepths[285] = 0; // Cutscene_ShadowBoss_1
	global.__objectDepths[286] = 0; // Cutscene_ShadowBoss_2
	global.__objectDepths[287] = 0; // Cutscene_GameEnd_1A
	global.__objectDepths[288] = 0; // Cutscene_GameEnd_1B
	global.__objectDepths[289] = 0; // Cutscene_MoaiOpenMouth_1
	global.__objectDepths[290] = 0; // Cutscene_MoaiOpenMouth2
	global.__objectDepths[291] = 0; // Cutscene_CreateWaterfall
	global.__objectDepths[292] = 0; // Cutscene_FloorTrap_1
	global.__objectDepths[293] = 0; // GameObjectG
	global.__objectDepths[294] = 0; // Exit
	global.__objectDepths[295] = 0; // HUD
	global.__objectDepths[296] = 0; // Menu
	global.__objectDepths[297] = 0; // PauseMenu
	global.__objectDepths[298] = 0; // LevelUpMenu
	global.__objectDepths[299] = 0; // DialogueWindow
	global.__objectDepths[300] = 0; // OptionsMenu
	global.__objectDepths[301] = 0; // QuitAppMenu
	global.__objectDepths[302] = 0; // TileSwapperStart
	global.__objectDepths[303] = 0; // TileSwapperEnd
	global.__objectDepths[304] = 0; // Dev_StabToCheat
	global.__objectDepths[305] = 0; // FrameIndicator
	global.__objectDepths[306] = 0; // ValDisplay2
	global.__objectDepths[307] = 0; // Tester1
	global.__objectDepths[308] = 0; // PaletteEditor
	global.__objectDepths[309] = 0; // Dev_RmWarper
	global.__objectDepths[310] = 0; // RandoDebug01
	global.__objectDepths[311] = 0; // GraphicsEffectsEditor
	global.__objectDepths[312] = 0; // Surface


	global.__objectNames[0] = "obj_start";
	global.__objectNames[1] = "obj_view_init";
	global.__objectNames[2] = "Audio";
	global.__objectNames[3] = "Sound";
	global.__objectNames[4] = "Input";
	global.__objectNames[5] = "g";
	global.__objectNames[6] = "p";
	global.__objectNames[7] = "f";
	global.__objectNames[8] = "RoomData";
	global.__objectNames[9] = "GameObjectData";
	global.__objectNames[10] = "Rando";
	global.__objectNames[11] = "DeathScreen";
	global.__objectNames[12] = "NextLifeScreen";
	global.__objectNames[13] = "GameOverScreen";
	global.__objectNames[14] = "ContinueSaveScreen";
	global.__objectNames[15] = "FileSelect";
	global.__objectNames[16] = "TitleScreen";
	global.__objectNames[17] = "Overworld";
	global.__objectNames[18] = "GameObjectMgr";
	global.__objectNames[19] = "GameObject";
	global.__objectNames[20] = "GameObjectA";
	global.__objectNames[21] = "Lonk";
	global.__objectNames[22] = "GameObjectB";
	global.__objectNames[23] = "GOB1";
	global.__objectNames[24] = "Enemy";
	global.__objectNames[25] = "Boss";
	global.__objectNames[26] = "Horsehead01";
	global.__objectNames[27] = "Helmethead01";
	global.__objectNames[28] = "HelmetheadHead01";
	global.__objectNames[29] = "Rebonack01A";
	global.__objectNames[30] = "Rebonack01B";
	global.__objectNames[31] = "Carock01";
	global.__objectNames[32] = "Gooma01";
	global.__objectNames[33] = "Barba01";
	global.__objectNames[34] = "Thunderbird01";
	global.__objectNames[35] = "ShadowLonk01";
	global.__objectNames[36] = "Ganon";
	global.__objectNames[37] = "Ganon1";
	global.__objectNames[38] = "Ganon2";
	global.__objectNames[39] = "Ganon3";
	global.__objectNames[40] = "Ache01";
	global.__objectNames[41] = "Aneru01";
	global.__objectNames[42] = "Aruroda01";
	global.__objectNames[43] = "Atta01";
	global.__objectNames[44] = "Backwall01";
	global.__objectNames[45] = "Bagin01";
	global.__objectNames[46] = "Bago01";
	global.__objectNames[47] = "Balshot01";
	global.__objectNames[48] = "Blaze01";
	global.__objectNames[49] = "Boggnipp01";
	global.__objectNames[50] = "Boon01";
	global.__objectNames[51] = "Bot";
	global.__objectNames[52] = "Bot_A";
	global.__objectNames[53] = "Bot_B";
	global.__objectNames[54] = "BoBoA";
	global.__objectNames[55] = "BubbA";
	global.__objectNames[56] = "CappA";
	global.__objectNames[57] = "DairA";
	global.__objectNames[58] = "DeelA";
	global.__objectNames[59] = "DoomA";
	global.__objectNames[60] = "FokkA";
	global.__objectNames[61] = "FokuA";
	global.__objectNames[62] = "GeldA";
	global.__objectNames[63] = "GlzmA";
	global.__objectNames[64] = "GeruA";
	global.__objectNames[65] = "GeruB";
	global.__objectNames[66] = "GiruA";
	global.__objectNames[67] = "GoriA";
	global.__objectNames[68] = "Growkke";
	global.__objectNames[69] = "MoblB";
	global.__objectNames[70] = "GumaA";
	global.__objectNames[71] = "IrKnA";
	global.__objectNames[72] = "LeevA";
	global.__objectNames[73] = "LowdA";
	global.__objectNames[74] = "MagnA";
	global.__objectNames[75] = "MagoA";
	global.__objectNames[76] = "Mau_A";
	global.__objectNames[77] = "MegmA";
	global.__objectNames[78] = "Moa_A";
	global.__objectNames[79] = "Moa_B";
	global.__objectNames[80] = "MoblA";
	global.__objectNames[81] = "MobyA";
	global.__objectNames[82] = "Myu_A";
	global.__objectNames[83] = "Octorok01";
	global.__objectNames[84] = "Ra__A";
	global.__objectNames[85] = "Slog";
	global.__objectNames[86] = "Snaraa";
	global.__objectNames[87] = "StfnA";
	global.__objectNames[88] = "StalA";
	global.__objectNames[89] = "Stallakk";
	global.__objectNames[90] = "TektA";
	global.__objectNames[91] = "TonnA";
	global.__objectNames[92] = "TyellManager";
	global.__objectNames[93] = "Tyell";
	global.__objectNames[94] = "Wheep";
	global.__objectNames[95] = "WizaA";
	global.__objectNames[96] = "WosuA";
	global.__objectNames[97] = "ZoraA";
	global.__objectNames[98] = "Kakusu";
	global.__objectNames[99] = "KakusuA";
	global.__objectNames[100] = "KakusuB";
	global.__objectNames[101] = "Kakusu000";
	global.__objectNames[102] = "Kakusu001";
	global.__objectNames[103] = "Kakusu002";
	global.__objectNames[104] = "Kakusu003";
	global.__objectNames[105] = "Kakusu004";
	global.__objectNames[106] = "Kakusu005";
	global.__objectNames[107] = "Kakusu006";
	global.__objectNames[108] = "Kakusu007";
	global.__objectNames[109] = "Kakusu008";
	global.__objectNames[110] = "Kakusu009";
	global.__objectNames[111] = "Kakusu010";
	global.__objectNames[112] = "Kakusu011";
	global.__objectNames[113] = "Kakusu012";
	global.__objectNames[114] = "Kakusu013";
	global.__objectNames[115] = "Kakusu014";
	global.__objectNames[116] = "GOB2";
	global.__objectNames[117] = "Spawner";
	global.__objectNames[118] = "SpawnerHostile";
	global.__objectNames[119] = "Spawner_Boggnipp";
	global.__objectNames[120] = "SpBaA";
	global.__objectNames[121] = "SpPoA";
	global.__objectNames[122] = "SpBuA";
	global.__objectNames[123] = "SpDrA";
	global.__objectNames[124] = "SpGrA";
	global.__objectNames[125] = "SpMaA";
	global.__objectNames[126] = "SpMoA";
	global.__objectNames[127] = "SpRoA";
	global.__objectNames[128] = "SpWoA";
	global.__objectNames[129] = "SpBlA";
	global.__objectNames[130] = "Spawner_FallingBlock";
	global.__objectNames[131] = "SpawnerFriendly";
	global.__objectNames[132] = "SpNPA";
	global.__objectNames[133] = "SpawnerStab";
	global.__objectNames[134] = "SpStA";
	global.__objectNames[135] = "NPC";
	global.__objectNames[136] = "NPC_0";
	global.__objectNames[137] = "NPC_1";
	global.__objectNames[138] = "NPC_2";
	global.__objectNames[139] = "NPC_3";
	global.__objectNames[140] = "NPC_4";
	global.__objectNames[141] = "NPC_5";
	global.__objectNames[142] = "NPC_6";
	global.__objectNames[143] = "NPC_7";
	global.__objectNames[144] = "NPC_8";
	global.__objectNames[145] = "NPC_9";
	global.__objectNames[146] = "NPC_A";
	global.__objectNames[147] = "NPC_B";
	global.__objectNames[148] = "NPC_C";
	global.__objectNames[149] = "NPC_D";
	global.__objectNames[150] = "Zelda";
	global.__objectNames[151] = "Item";
	global.__objectNames[152] = "ItmA0";
	global.__objectNames[153] = "ItmA1";
	global.__objectNames[154] = "ItmA2";
	global.__objectNames[155] = "ItmA3";
	global.__objectNames[156] = "ItmA4";
	global.__objectNames[157] = "ItmA5";
	global.__objectNames[158] = "ItmA6";
	global.__objectNames[159] = "ItmA7";
	global.__objectNames[160] = "ItmA8";
	global.__objectNames[161] = "ItmA9";
	global.__objectNames[162] = "ItmAA";
	global.__objectNames[163] = "ItmAB";
	global.__objectNames[164] = "ItmAC";
	global.__objectNames[165] = "ItmAD";
	global.__objectNames[166] = "ItmAE";
	global.__objectNames[167] = "ItmAF";
	global.__objectNames[168] = "ItmK0";
	global.__objectNames[169] = "ItmK1";
	global.__objectNames[170] = "ItmK2";
	global.__objectNames[171] = "ItmK3";
	global.__objectNames[172] = "ItmK4";
	global.__objectNames[173] = "ItmK5";
	global.__objectNames[174] = "ItmK6";
	global.__objectNames[175] = "ItmK7";
	global.__objectNames[176] = "ItmK8";
	global.__objectNames[177] = "ItmK9";
	global.__objectNames[178] = "ItmKA";
	global.__objectNames[179] = "ItmKB";
	global.__objectNames[180] = "ItmD8";
	global.__objectNames[181] = "ItmB0";
	global.__objectNames[182] = "ItmB1";
	global.__objectNames[183] = "ItmC0";
	global.__objectNames[184] = "ItmC1";
	global.__objectNames[185] = "ItmC2";
	global.__objectNames[186] = "ItmC3";
	global.__objectNames[187] = "ItmC4";
	global.__objectNames[188] = "ItmC5";
	global.__objectNames[189] = "ItmD0";
	global.__objectNames[190] = "ItmE0";
	global.__objectNames[191] = "ItmF0";
	global.__objectNames[192] = "ItmG0";
	global.__objectNames[193] = "ItmH0";
	global.__objectNames[194] = "ItmS0";
	global.__objectNames[195] = "Elevator";
	global.__objectNames[196] = "ElevA";
	global.__objectNames[197] = "ElevatorB";
	global.__objectNames[198] = "LoDoA";
	global.__objectNames[199] = "ReFaA";
	global.__objectNames[200] = "CrHoA";
	global.__objectNames[201] = "BarrA";
	global.__objectNames[202] = "Barrier2";
	global.__objectNames[203] = "FaBlA";
	global.__objectNames[204] = "BlckB";
	global.__objectNames[205] = "SpikeTrap";
	global.__objectNames[206] = "SpTrA";
	global.__objectNames[207] = "SpTrB";
	global.__objectNames[208] = "SpTrC";
	global.__objectNames[209] = "SpikeTrapD";
	global.__objectNames[210] = "Switch";
	global.__objectNames[211] = "SwchA";
	global.__objectNames[212] = "SwchB";
	global.__objectNames[213] = "PushA";
	global.__objectNames[214] = "PushableRefresher";
	global.__objectNames[215] = "Target";
	global.__objectNames[216] = "TargA";
	global.__objectNames[217] = "FiRoA";
	global.__objectNames[218] = "Torch";
	global.__objectNames[219] = "TorchA";
	global.__objectNames[220] = "ArenaGate";
	global.__objectNames[221] = "ArenaGateA";
	global.__objectNames[222] = "Cucco";
	global.__objectNames[223] = "Blooby";
	global.__objectNames[224] = "Eyenocc";
	global.__objectNames[225] = "SmasherTrapManager";
	global.__objectNames[226] = "SmasherTrap";
	global.__objectNames[227] = "SmasherTrap01";
	global.__objectNames[228] = "GameObjectC";
	global.__objectNames[229] = "ProjectileHostile";
	global.__objectNames[230] = "Axe";
	global.__objectNames[231] = "Bolo";
	global.__objectNames[232] = "Boomerang";
	global.__objectNames[233] = "Bullet1";
	global.__objectNames[234] = "Bullet2";
	global.__objectNames[235] = "Drop";
	global.__objectNames[236] = "Fireball1";
	global.__objectNames[237] = "Fireball2";
	global.__objectNames[238] = "Flame1";
	global.__objectNames[239] = "Flame2";
	global.__objectNames[240] = "Mace1";
	global.__objectNames[241] = "Mace2";
	global.__objectNames[242] = "RisingBubble";
	global.__objectNames[243] = "Rock1";
	global.__objectNames[244] = "Rock2";
	global.__objectNames[245] = "Rock3";
	global.__objectNames[246] = "SoundWave";
	global.__objectNames[247] = "Spear";
	global.__objectNames[248] = "SwordBeam";
	global.__objectNames[249] = "BossExplosion";
	global.__objectNames[250] = "SpikeBall1";
	global.__objectNames[251] = "ProjectileFriendly";
	global.__objectNames[252] = "GameObjectD";
	global.__objectNames[253] = "Platform";
	global.__objectNames[254] = "PlatformA";
	global.__objectNames[255] = "PlatformB";
	global.__objectNames[256] = "PlatformCloud";
	global.__objectNames[257] = "PlatformRaft";
	global.__objectNames[258] = "BurnableMgr";
	global.__objectNames[259] = "GameObjectE";
	global.__objectNames[260] = "Challenge";
	global.__objectNames[261] = "Challenge_BlockConfiguration";
	global.__objectNames[262] = "Challenge_IntermittentPlatformSequence";
	global.__objectNames[263] = "Challenge_SwitchA";
	global.__objectNames[264] = "Challenge_SwitchB";
	global.__objectNames[265] = "Challenge_SwitchC";
	global.__objectNames[266] = "Challenge_SwitchD";
	global.__objectNames[267] = "MiniGame";
	global.__objectNames[268] = "MnGmA";
	global.__objectNames[269] = "TogglingPathDirection";
	global.__objectNames[270] = "TogglingPathDirectionA";
	global.__objectNames[271] = "TogglingPathDirectionB";
	global.__objectNames[272] = "Challenge_DefeatAll";
	global.__objectNames[273] = "Challenge_DefeatAllA";
	global.__objectNames[274] = "Challenge_LightTorches";
	global.__objectNames[275] = "Challenge_LightTorchesA";
	global.__objectNames[276] = "Challenge_SpellSequence";
	global.__objectNames[277] = "Challenge_SpellSequenceA";
	global.__objectNames[278] = "Challenge_PushableMatching1";
	global.__objectNames[279] = "Challenge_Secret01";
	global.__objectNames[280] = "GameObjectF";
	global.__objectNames[281] = "Cutscene";
	global.__objectNames[282] = "Cutscene_SariaBridge";
	global.__objectNames[283] = "Cutscene_MagicalKeyHouse";
	global.__objectNames[284] = "Cutscene_EnterFromChimney";
	global.__objectNames[285] = "Cutscene_ShadowBoss_1";
	global.__objectNames[286] = "Cutscene_ShadowBoss_2";
	global.__objectNames[287] = "Cutscene_GameEnd_1A";
	global.__objectNames[288] = "Cutscene_GameEnd_1B";
	global.__objectNames[289] = "Cutscene_MoaiOpenMouth_1";
	global.__objectNames[290] = "Cutscene_MoaiOpenMouth2";
	global.__objectNames[291] = "Cutscene_CreateWaterfall";
	global.__objectNames[292] = "Cutscene_FloorTrap_1";
	global.__objectNames[293] = "GameObjectG";
	global.__objectNames[294] = "Exit";
	global.__objectNames[295] = "HUD";
	global.__objectNames[296] = "Menu";
	global.__objectNames[297] = "PauseMenu";
	global.__objectNames[298] = "LevelUpMenu";
	global.__objectNames[299] = "DialogueWindow";
	global.__objectNames[300] = "OptionsMenu";
	global.__objectNames[301] = "QuitAppMenu";
	global.__objectNames[302] = "TileSwapperStart";
	global.__objectNames[303] = "TileSwapperEnd";
	global.__objectNames[304] = "Dev_StabToCheat";
	global.__objectNames[305] = "FrameIndicator";
	global.__objectNames[306] = "ValDisplay2";
	global.__objectNames[307] = "Tester1";
	global.__objectNames[308] = "PaletteEditor";
	global.__objectNames[309] = "Dev_RmWarper";
	global.__objectNames[310] = "RandoDebug01";
	global.__objectNames[311] = "GraphicsEffectsEditor";
	global.__objectNames[312] = "Surface";


	// create another array that has the correct entries
	var len = array_length(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
